[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "cspr-contracts"
authors = [{name = "Hector Miranda", email = "marcetux@gmail.com"}]
dynamic = ["version", "description"]
